name: COMET
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - biopython=1.85
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - numpy
  - pandas
  - pysam
  - tqdm
  - minimap2
  - k8